name: Front End Workflows

on:
  push:
    branches: ["*"]
  pull_request:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref_name == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        with:
          args: deploy --dir=build --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID", "REACT_APP_API_URL"]'